// GraphActiveX.idl: источник языка IDL для GraphActiveX
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(3b3b5f67-0de0-48e0-96f6-9dfdf21f7488),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IGraphCtl : IDispatch
{
	[propput, bindable, requestedit, id(DISPID_BACKCOLOR)]
	HRESULT BackColor([in]OLE_COLOR clr);
	[propget, bindable, requestedit, id(DISPID_BACKCOLOR)]
	HRESULT BackColor([out,retval]OLE_COLOR* pclr);
	[propput, bindable, requestedit, id(DISPID_FORECOLOR)]
	HRESULT ForeColor([in]OLE_COLOR clr);
	[propget, bindable, requestedit, id(DISPID_FORECOLOR)]
	HRESULT ForeColor([out,retval]OLE_COLOR* pclr);
	[propget, id(1), helpstring("Минимальное значение x")] HRESULT MinX([out, retval] SHORT* pVal);
	[propput, id(1), helpstring("Минимальное значение x")] HRESULT MinX([in] SHORT newVal);
	[propget, id(2), helpstring("Максимальное значение X")] HRESULT MaxX([out, retval] SHORT* pVal);
	[propput, id(2), helpstring("Максимальное значение X")] HRESULT MaxX([in] SHORT newVal);
	[propget, id(3), helpstring("Минимальное значение y")] HRESULT MinY([out, retval] SHORT* pVal);
	[propput, id(3), helpstring("Минимальное значение y")] HRESULT MinY([in] SHORT newVal);
	[propget, id(4), helpstring("Максимальное значение y")] HRESULT MaxY([out, retval] SHORT* pVal);
	[propput, id(4), helpstring("Максимальное значение y")] HRESULT MaxY([in] SHORT newVal);
};

[
	uuid(60818e62-e786-4da7-b7d0-dfe0b3997ad9),
	version(1.0),
]
library GraphActiveXLib
{
	importlib("stdole2.tlb");
	[
		uuid(ce61696e-d646-4886-a457-d5ff6ad776b0)
	]
	dispinterface _IGraphCtlEvents
	{
		properties:
		methods:
			[id(1), helpstring("Отобразить график")] void ShowGraph([in] VARIANT_BOOL sb);
	};
	[
		uuid(439e1d31-62c7-4436-a938-490d0f4059ea),
		control
	]
	coclass GraphCtl
	{
		[default] interface IGraphCtl;
		[default, source] dispinterface _IGraphCtlEvents;
	};
};

